name: vbench2
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - psutil=5.9.0=py310h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - albucore==0.0.19
      - albumentations==1.4.19
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - args==0.1.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrdict==2.0.1
      - attrs==24.3.0
      - av==14.0.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.12.3
      - binpacking==1.5.2
      - bitsandbytes==0.42.0
      - blinker==1.9.0
      - blis==1.2.0
      - boto3==1.26.90
      - botocore==1.29.165
      - braceexpand==0.1.7
      - brotli==1.1.0
      - cachetools==6.1.0
      - catalogue==2.0.10
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - clint==0.5.1
      - cloudpathlib==0.21.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - confection==0.1.5
      - configobj==5.0.9
      - contourpy==1.3.1
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cryptography==45.0.5
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==3.1.2
      - dacite==1.9.2
      - datasets==3.2.0
      - decorator==5.1.1
      - decord==0.6.0
      - deep-sort-realtime==1.3.2
      - deepspeed==0.14.4
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - diffusers==0.32.1
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - easydict==1.13
      - einops==0.8.0
      - einops-exts==0.0.4
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fabric==3.2.2
      - fairscale==0.4.13
      - fastapi==0.115.6
      - ffmpy==0.6.0
      - filelock==3.13.1
      - filterpy==1.4.5
      - fire==0.4.0
      - flash-attn==2.7.2.post1
      - flatbuffers==25.2.10
      - flowlib==0.6.6.8
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gast==0.6.0
      - gdown==5.2.0
      - gevent==25.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-pasta==0.2.0
      - gradio==5.38.0
      - gradio-client==1.11.0
      - greenlet==3.2.3
      - groovy==0.1.2
      - grpcio==1.73.1
      - h11==0.14.0
      - h5py==3.12.1
      - hjson==3.1.0
      - hpsv2==1.2.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.0
      - humanfriendly==10.0
      - idna==3.10
      - iglovikov-helper-functions==0.0.53
      - imagecorruptions==1.1.2
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - invoke==2.2.0
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipython==8.32.0
      - jax==0.6.2
      - jaxlib==0.6.2
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.3
      - jiter==0.8.2
      - jmespath==0.10.0
      - joblib==1.4.2
      - jpeg4py==0.1.4
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - keras==3.10.0
      - kiwisolver==1.4.8
      - kornia==0.5.6
      - kornia-rs==0.1.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - llava==1.7.0.dev0
      - logger==1.4
      - lvis==0.5.3
      - marisa-trie==1.2.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mediapipe==0.10.11
      - ml-dtypes==0.5.1
      - mmcv==2.2.0
      - mmcv-lite==2.2.0
      - mmdet==3.0.0
      - mmengine==0.10.5
      - mmyolo==0.6.0
      - model-index==0.1.11
      - modelscope==1.28.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.12
      - namex==0.1.0
      - narwhals==1.48.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numpy==1.26.3
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime==1.16.3
      - open-clip-torch==2.30.0
      - openai==1.59.5
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.0.11
      - opt-einsum==3.4.0
      - optree==0.16.0
      - ordered-set==4.1.0
      - orjson==3.11.0
      - oss2==2.19.1
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.2.3
      - paramiko==3.5.1
      - parso==0.8.4
      - peft==0.15.2
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==3.1.1
      - preshed==3.0.9
      - prettytable==3.14.0
      - prompt-toolkit==3.0.51
      - propcache==0.2.1
      - protobuf==3.20.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pybboxes==0.1.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pydeck==0.9.1
      - pydub==0.25.1
      - pyecharts==2.0.8
      - pygments==2.19.2
      - pynacl==1.5.0
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - pytest==7.2.0
      - pytest-split==0.8.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyyaml==6.0.2
      - qudida==0.0.4
      - qwen-vl-utils==0.0.11
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - retina-face==0.0.17
      - retinaface-pytorch==0.0.8
      - rich==13.9.4
      - rouge==1.0.1
      - rpds-py==0.26.0
      - ruff==0.12.4
      - s3transfer==0.6.2
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - sahi==0.11.31
      - scenedetect==0.6.5.2
      - scikit-image==0.25.0
      - scikit-learn==1.6.0
      - scipy==1.15.0
      - seaborn==0.13.2
      - selenium==4.29.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - sh==2.2.2
      - shapely==2.0.7
      - shellingham==1.5.4
      - simplejson==3.20.1
      - six==1.17.0
      - smart-open==7.3.0.post1
      - smmap==5.0.2
      - snapshot-selenium==0.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sounddevice==0.5.2
      - soupsieve==2.6
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - starlette==0.41.3
      - streamlit==1.47.0
      - stringzilla==3.12.5
      - supervision==0.19.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminaltables==3.1.10
      - tf-keras==2.19.0
      - thinc==8.3.4
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - tiktoken==0.8.0
      - timesformer-pytorch==0.4.1
      - timm==0.4.12
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.0
      - transformers-stream-generator==0.0.5
      - trio==0.30.0
      - trio-websocket==0.12.2
      - triton==3.1.0
      - trl==0.19.1
      - typer==0.16.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - ultralytics==8.3.68
      - ultralytics-thop==2.0.14
      - unicorn==2.1.1
      - urllib3==1.26.15
      - uvicorn==0.35.0
      - wandb==0.19.2
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webdataset==0.2.100
      - websocket==0.2.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wordcloud==1.9.4
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.18.3
      - yolo-world==0.1.0
      - yolov5==7.0.10
      - zipp==3.21.0
      - zope-event==5.1
      - zope-interface==7.2
      - zstandard==0.23.0
prefix: ./anaconda3/envs/vbench2
